set-option -g prefix C-e
unbind-key C-e
bind-key C-e send-prefix

set-window-option -g mode-keys vi

# Make OS X Terminal.app give us the full color experience.
set-option -g default-terminal "screen-256color"

# Fix weirdness with OS X bootstrap namespaces and daemon.
# See https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard for details.
set-option -g default-command "reattach-to-user-namespace -l /usr/local/bin/fish"

## Next bit from
## http://robots.thoughtbot.com/post/55885045171/tmux-copy-paste-on-os-x-a-better-future
## Works as of tmux 1.8.
# Use vim keybindings in copy mode
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
bind-key -t vi-copy v begin-selection
bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -t vi-copy Enter
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
## END thoughtbot ##

# Use vim motion keys for directional pane selection rather than arrow keys.
bind-key C-h select-pane -L
bind-key C-j select-pane -D
bind-key C-k select-pane -U
bind-key C-l select-pane -R  # careful not to stomp last-window binding!
