set-option -g prefix C-e
unbind-key C-e
bind-key C-e send-prefix
# Remove the default prefix binding
unbind-key C-b

set-window-option -g mode-keys vi

set-option -g set-titles on
set-option -g status-position top

# Enable scrolling with the mouse.
set-option -g mouse on
# Fix swipe-highlighting.
# Via: https://www.reddit.com/r/tmux/comments/nyu2ka/comment/h1m45jw/
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-no-clear "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear "reattach-to-user-namespace pbcopy"

# Let it know Ghostty can handle OSC-8 hyperlinks.
set -as terminal-features ',xterm-ghostty:hyperlinks'

# Increase scrollback buffer size
set-option -g history-limit 50000

# Display messages for longer
set-option -g display-time 4000

# Refresh left/right status more often
set-option -g status-interval 5

# Make OS X Terminal.app give us the full color experience.
set-option -s default-terminal "screen-256color"

# Enable focus events
set-option -g focus-events on

# Fix weirdness with OS X bootstrap namespaces and daemon.
# See https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard for details.
set-option -g default-command "reattach-to-user-namespace -l /usr/local/bin/fish"

## Next bit from
## http://robots.thoughtbot.com/post/55885045171/tmux-copy-paste-on-os-x-a-better-future
## Works as of tmux 1.8.
# Use vim keybindings in copy mode
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
bind-key -Tcopy-mode-vi v send -X begin-selection
bind-key -Tcopy-mode-vi y send -X copy-pipe "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -Tcopy-mode-vi Enter
bind-key -Tcopy-mode-vi Enter send -X copy-pipe "reattach-to-user-namespace pbcopy"
## END thoughtbot ##

# Use vim motion keys for directional pane selection rather than arrow keys.
bind-key C-h select-pane -L
bind-key C-j select-pane -D
bind-key C-k select-pane -U
bind-key C-l select-pane -R  # careful not to stomp last-window binding!

# Enable next/prev window shortcuts
bind-key C-p previous-window
bind-key C-n next-window

# Make it easier to refresh config
bind-key R run-shell " \
  tmux source-file ~/.tmux.conf > /dev/null; \
  tmux display-message 'Sourced ~/.tmux.conf'"

# Tmux Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Enable automatic restoration
set -g @continuum-restore 'on'

if '[ -f ~/.tmux/plugins/tpm/tpm ]' {
    run '~/.tmux/plugins/tpm/tpm'
}
