# Via: https://github.com/helix-editor/helix/issues/3842#issuecomment-4089027714
inherits = "default"
"ui.cursor.normal" = { bg = "dark-gray" }
"ui.cursor.insert" = { bg = "dark-gray" }
"ui.cursor.primary.select" = { bg = "light-delta" }
"ui.selection.primary" = { bg = "light-purple" }

[palette]
dark-gray = "#aaaaaa"
light-delta = "#977bed"
light-purple = "#7500d6"
