## Use repo-local `prettier` to fix up files.
#[fix.tools.prettier]
#command = ["corepack", "pnpm", "exec", "prettier", "--ignore-unknown", "--stdin-filepath=$path"]
#patterns = [
#    "glob:'**/*.tsx'", "glob:'**/*.ts'",
#    "glob:'**/*.jsx'", "glob:'**/*.mjs'", "glob:'**/*.js'",
#    "glob:'**/*.mts'", "glob:'**/*.cts'",
#    "glob:'**/*.css'", "glob:'**/*.html'",
#    "glob:'**/*.yml'", "glob:'**/*.yaml'"
#    ]
