# Start on server with: synergys --name bnr --config ~/.config/synergy.conf
# Start on client with: synergyc -f --name cricket 10.0.0.2
# -f foregrounds it so you can see what's going on.
section: screens
    bnr:
    cricket:
end

section: links
    bnr:
        down(20, 80) = cricket

    cricket:
        up = bnr
end

section: aliases
    bnr:
        J-Shermal.local
    cricket:
        M-C02FR48NMD6R
end

section: options
    switchDelay = 10 # ms delay before switching screens
    clipboardSharing = true
    clipboardSharingSize = 10000 # kB limit on sharing size
end
