[settings.logs]
time_retention = "7d"
line_retention = 10_000

[settings.proxy]
enable = true

[slugs.shop]
namespace = "0"
daemon = "plantshop-frontend"

[namespaces.0]
dir = "/Users/jeremy/git/sells-plants/0"
