# @generated by usage-cli from usage spec

set -l commands activate boot clean daemons completion disable enable list logs mcp proxy restart run settings sponsors start status stop supervisor tui wait help
set -l daemon_commands status logs start stop restart disable enable wait

function __pitchfork_daemons
    pitchfork list --hide-header | cut -d' ' -f1
end

function __unseen_pitchfork_daemons
    set -l existing (commandline -opc | tail -n +2)
    for daemon in (__pitchfork_daemons)
        if not contains -- $daemon $existing
            echo $daemon
        end
    end
end


# if "usage" is not installed show an error
if ! type -p usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in pitchfork." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_pitchfork.spec"
pitchfork usage | string collect > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc pitchfork -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc pitchfork -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end

complete --command pitchfork \
    --condition "__fish_seen_subcommand_from $daemon_commands" \
    --no-files --arguments "(__unseen_pitchfork_daemons)"
