[tools]
node = "24"
"npm:corepack" = "latest"
pitchfork = "latest"

[settings]
activate_aggressive = true
auto_env = true
env_file = '.env.local'
env_shell_expand = true
python.uv_venv_auto = "source"
